# Generated by Django 4.2 on 2025-07-20 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('trip_category', models.CharField(choices=[('Intrastate', 'Intrastate'), ('Interstate', 'Interstate')], max_length=15)),
                ('trip_type', models.CharField(choices=[('Flexible', 'Flexible'), ('Express', 'Express')], max_length=10)),
                ('date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('total_seats', models.PositiveSmallIntegerField()),
                ('available_seats', models.PositiveSmallIntegerField()),
                ('base_price', models.PositiveIntegerField()),
                ('passenger_price', models.PositiveIntegerField()),
                ('pickup_point', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
