# Generated by Django 4.2 on 2025-07-20 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardwithmeAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('preferred_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('vehicle_type', models.CharField(max_length=50)),
                ('total_seats_needed', models.PositiveSmallIntegerField()),
                ('seats_booked', models.PositiveSmallIntegerField(default=0)),
                ('base_price', models.PositiveIntegerField()),
                ('passenger_price', models.PositiveIntegerField()),
                ('pickup_point', models.CharField(max_length=255)),
                ('status', models.CharField(default='open', max_length=15)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
