# Generated by Django 4.2 on 2025-07-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='license_file',
            field=models.FileField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_file',
            field=models.FileField(blank=True, null=True, upload_to='vehicles/'),
        ),
    ]
