# Generated by Django 4.2 on 2025-07-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_license_file_user_vehicle_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='driver_type',
            field=models.CharField(blank=True, choices=[('freelance', 'Freelance'), ('garage', 'Garage-affiliated')], max_length=20),
        ),
    ]
